train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/celebAHQ/32
      root_path_2: ./load/celebAHQ/256
      split_file: ./load/celebAHQ/split.json
      split_key: train
      cache: bin
  wrapper:
    name: sr-implicit-uniform-varied
    args:
      size_min: 32
      size_max: 256
      gt_resize: 256
      sample_q: 1024
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/celebAHQ/32
      root_path_2: ./load/celebAHQ/256
      split_file: ./load/celebAHQ/split.json
      split_key: val
      first_k: 100
      cache: bin
  wrapper:
    name: sr-implicit-paired
    args:
      sample_q: 1024
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        scale: 8

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 200
multi_step_lr:
  milestones: [100]
  gamma: 0.1

epoch_val: 1
epoch_save: 100
